% Startup commands and graphics defaults
% Biafra Ahanonu
% started: 2013.12.07 [17:28:44]

loadBatchFxns

% set default figure properties
setFigureDefaults();

% % set(0,'DefaultFigureWindowStyle','docked');
% % set defaults for graphics
% display('setting graphics defaults...')
% % scnsize = get(0,'ScreenSize');
% % pos1 = [scnsize(3)/2, 10, scnsize(3)/2-20, scnsize(4)-100];
% % 'DefaultTextInterpreter','Tex',...
% set(0, 'DefaultFigureColor', 'White',...
% 'DefaultTextInterpreter','Tex',...
% 'DefaultFigurePaperType', 'a4letter', ...
% 'DefaultFigureWindowStyle','docked',...
% 'DefaultAxesColor', 'white', ...
% 'DefaultAxesDrawmode', 'fast', ...
% 'DefaultAxesFontUnits', 'points', ...
% 'DefaultAxesFontSize', 20, ...
% 'DefaultAxesFontAngle', 'Normal', ...
% 'DefaultAxesFontName', 'Arial', ...
% 'DefaultAxesGridLineStyle', ':', ...
% 'DefaultAxesInterruptible', 'on', ...
% 'DefaultAxesLayer', 'Bottom', ...
% 'DefaultAxesNextPlot', 'replace', ...
% 'DefaultAxesUnits', 'normalized', ...
% 'DefaultAxesXcolor', [0, 0, 0], ...
% 'DefaultAxesYcolor', [0, 0, 0], ...
% 'DefaultAxesZcolor', [0, 0, 0], ...
% 'DefaultAxesVisible', 'on', ...
% 'DefaultLineColor', 'Red', ...
% 'DefaultLineLineStyle', '-', ...
% 'DefaultLineLineWidth', 0.5, ...
% 'DefaultLineMarker', 'none', ...
% 'DefaultLineMarkerSize', 8, ...
% 'DefaultTextColor', [0, 0, 0], ...
% 'DefaultTextFontUnits', 'Points', ...
% 'DefaultTextFontSize', 20, ...
% 'DefaultTextFontName', 'Arial', ...
% 'DefaultTextVerticalAlignment', 'middle', ...
% 'DefaultTextHorizontalAlignment', 'left',...
% 'DefaultPatchFaceColor',[0 0 0],...
% 'DefaultPatchEdgeColor','w'...
% );
% % 'DefaultFigurePosition',pos1,...

% iptsetpref('ImshowInitialMagnification', 'fit')