function setFigureDefaults()
	% Sets preferred figure defaults.
	% Biafra Ahanonu
	% started: 2013.10.29
	% inputs
		%
	% outputs
		%

	% changelog
		% 2022.11.02 [17:06:11] - Disable Matlab UI font size change for code and text, that is left to the user.
	% TODO
		%

	disp('Setting graphics defaults...')

	% scnsize = get(0,'ScreenSize');
	% pos1 = [scnsize(3)/2, 10, scnsize(3)/2-20, scnsize(4)-100];
	% defaultFontStr = 'Futura Std Book';
	% defaultUIFontStr = 'Arial';

	% defaultFontStr = 'Futura Std Book';
	% defaultUIFontStr = 'Futura Std Book';

	defaultFontStr = 'Consolas';
	defaultUIFontStr = 'Consolas';

	% java.awt.Font.BOLD
	if ismac
		cmdWinEditorFont = 'Menlo-Regular';
	elseif isunix
	    cmdWinEditorFont = 'Consolas';
	elseif ispc
		cmdWinEditorFont = 'Consolas';
	else
	    disp('Platform not supported')
	end

	% Change the command window and editor fonts
	% FontSize = 9;
	% com.mathworks.services.FontPrefs.setCodeFont(java.awt.Font(cmdWinEditorFont,0,FontSize*2))
 %    com.mathworks.services.FontPrefs.setTextFont(java.awt.Font(cmdWinEditorFont,0,FontSize*2))

	% 'DefaultLineLineSmoothing','on',...
	% 'DefaultPatchLineSmoothing','on',...
	% set(0,'DefaultFigureWindowStyle','docked')
	% 'DefaultFigurePosition',pos1,...

	% Set color order back to default
	set(groot,'DefaultAxesColorOrder','factory')

	set(0, 'DefaultFigureColor', 'White',...
		'defaulttextinterpreter','tex',...
	'DefaultFigurePaperType', 'a4letter', ...
	'DefaultFigureWindowStyle','docked',...
	'DefaultAxesColor', 'white', ...
	'DefaultAxesDrawmode', 'fast', ...
	'DefaultAxesFontUnits', 'points', ...
	'DefaultAxesFontSize', 9, ...
	'DefaultAxesFontAngle', 'Normal', ...
	'DefaultAxesFontName', defaultFontStr, ...
	'DefaultAxesGridLineStyle', ':', ...
	'DefaultAxesInterruptible', 'on', ...
	'DefaultAxesLayer', 'Bottom', ...
	'DefaultAxesLineWidth', 2, ...
	'DefaultAxesNextPlot', 'replace', ...
	'DefaultAxesUnits', 'normalized', ...
	'DefaultAxesXcolor', [0, 0, 0], ...
	'DefaultAxesYcolor', [0, 0, 0], ...
	'DefaultAxesZcolor', [0, 0, 0], ...
	'DefaultAxesVisible', 'on', ...
	'DefaultLineColor', 'Red', ...
	'DefaultLineLineStyle', '-', ...
	'DefaultLineLineWidth', 0.5, ...
	'DefaultLineMarker', 'none', ...
	'DefaultLineMarkerSize', 8, ...
	'DefaultTextColor', [0, 0, 0], ...
	'DefaultTextFontUnits', 'Points', ...
	'DefaultTextFontSize', 9, ...
	'DefaultTextFontName', defaultFontStr, ...
	'DefaultUIControlFontName', defaultUIFontStr, ...
	'DefaultUIControlFontSize', 16, ...
	'DefaultTextVerticalAlignment', 'middle', ...
	'DefaultTextHorizontalAlignment', 'left',...
	'DefaultPatchFaceColor',[0 0 0],...
	'DefaultPatchEdgeColor','w',...
	'DefaultAxesTickDir','out',...
	'DefaultAxesTickDirMode', 'manual',...
	'defaultAxesBox','off'...
	);

	iptsetpref('ImshowInitialMagnification', 'fit')
	% set(gca, 'Position', get(gca, 'OuterPosition') - ...
	%     get(gca, 'TightInset') * [-1 0 1 0; 0 -1 0 1; 0 0 1 0; 0 0 0 1]);
end
