function obj = setMovieInfo(obj)
	% Settings for movie and cell extraction inputs and outputs.
	% Biafra Ahanonu
	% started: 2014.07.31 - branch from calciumImagingAnalysis 2020.05.07 [15:47:29]
	% inputs
		%
	% outputs
		%

	% changelog
		%
	% TODO
		%

	movieSettings = inputdlg({...
			'Regular expression for raw files (e.g. if raw files all have "concat" in the name, put "concat"): ',...
			'Regular expression for processed files, skip if no processed files (e.g. if processed files all have "dfof" in the name, put "dfof"): ',...
			'[optional, if using HDF5 or NWB] Input HDF5 (or NWB movie) file dataset name (e.g. "/images" for raw Inscopix or "/1" for example data, sans quotes): ',...
			'[optional, if using NWB files] Regular expression for NWB cell-extraction file name (e.g. "ICA" for if file called "myExperiment_ICA.nwb"): ',...
			'[optional, if using NWB files] Sub-folder where NWB cell-extraction files are located (leave blank of in root folder [no sub-folder]): '...
		},...
		'Movie information',[1 100],...
		{...
			obj.fileFilterRegexpRaw,...
			obj.fileFilterRegexp,...
			obj.inputDatasetName,...
			obj.nwbFileRegexp,...
			obj.nwbFileFolder...
		}...
	);
	obj.fileFilterRegexpRaw = movieSettings{1};
	obj.fileFilterRegexp = movieSettings{2};
	obj.inputDatasetName = movieSettings{3};
	obj.nwbFileRegexp = movieSettings{4};
	obj.nwbFileFolder = movieSettings{5};
end