function setFigureDefaults()
	% Sets preferred figure defaults
	% Biafra Ahanonu
	% started: 2013.10.29
	% inputs
		%
	% outputs
		%

	% changelog
		%
	% TODO
		%

	display('Setting graphics defaults...')

	% scnsize = get(0,'ScreenSize');
	% pos1 = [scnsize(3)/2, 10, scnsize(3)/2-20, scnsize(4)-100];
	defaultFontStr = 'Futura Std Book';
	defaultUIFontStr = 'Arial';
	% 'DefaultLineLineSmoothing','on',...
	% 'DefaultPatchLineSmoothing','on',...
	% set(0,'DefaultFigureWindowStyle','docked')
	% 'DefaultFigurePosition',pos1,...
	set(0, 'DefaultFigureColor', 'White',...
		'defaulttextinterpreter','tex',...
	'DefaultFigurePaperType', 'a4letter', ...
	'DefaultFigureWindowStyle','docked',...
	'DefaultAxesColor', 'white', ...
	'DefaultAxesDrawmode', 'fast', ...
	'DefaultAxesFontUnits', 'points', ...
	'DefaultAxesFontSize', 9, ...
	'DefaultAxesFontAngle', 'Normal', ...
	'DefaultAxesFontName', defaultFontStr, ...
	'DefaultAxesGridLineStyle', ':', ...
	'DefaultAxesInterruptible', 'on', ...
	'DefaultAxesLayer', 'Bottom', ...
	'DefaultAxesLineWidth', 2, ...
	'DefaultAxesNextPlot', 'replace', ...
	'DefaultAxesUnits', 'normalized', ...
	'DefaultAxesXcolor', [0, 0, 0], ...
	'DefaultAxesYcolor', [0, 0, 0], ...
	'DefaultAxesZcolor', [0, 0, 0], ...
	'DefaultAxesVisible', 'on', ...
	'DefaultLineColor', 'Red', ...
	'DefaultLineLineStyle', '-', ...
	'DefaultLineLineWidth', 0.5, ...
	'DefaultLineMarker', 'none', ...
	'DefaultLineMarkerSize', 8, ...
	'DefaultTextColor', [0, 0, 0], ...
	'DefaultTextFontUnits', 'Points', ...
	'DefaultTextFontSize', 9, ...
	'DefaultTextFontName', defaultFontStr, ...
	'DefaultUIControlFontName', defaultUIFontStr, ...
	'DefaultUIControlFontSize', 16, ...
	'DefaultTextVerticalAlignment', 'middle', ...
	'DefaultTextHorizontalAlignment', 'left',...
	'DefaultPatchFaceColor',[0 0 0],...
	'DefaultPatchEdgeColor','w',...
	'DefaultAxesTickDir','out',...
	'DefaultAxesTickDirMode', 'manual',...
	'defaultAxesBox','off'...
	);

	iptsetpref('ImshowInitialMagnification', 'fit')
end

% set(gca, 'Position', get(gca, 'OuterPosition') - ...
%     get(gca, 'TightInset') * [-1 0 1 0; 0 -1 0 1; 0 0 1 0; 0 0 0 1]);